stages:
  - Lint
  - Test
  - Docker
  - Deploy

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - ~/.cache/pip/

.template: &build
  image: python:latest
  before_script:
    - python -V
    - pip install -r darkflow/requirements.txt

format:
  stage: Lint
  image: python:latest
  script:
    - pip install black
    - black ./darkflow/

lint:
  stage: Lint
  <<: *build
  script:
    - pip install pylint
    - pylint --exit-zero darkflow/

test:
  stage: Test
  <<: *build
  script:
    - echo 'Testing...'

docker:
  stage: Docker
  image: docker:stable
  only:
    - master
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  script:
    - echo "Building and uploading Docker image ðŸ³"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH ./darkflow/
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH

deploy:
  stage: Deploy
  trigger: my-life-ua/compose
  only:
    - master

